# Generated by Django 2.2.10 on 2021-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
