# Generated by Django 2.2.10 on 2021-01-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0010_auto_20210101_2057'),
        ('news', '0002_news_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumni_profile.Alumni_Profile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200),
        ),
    ]
