# Generated by Django 2.2.10 on 2020-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
