# Generated by Django 2.2.10 on 2020-11-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0007_auto_20201115_1143'),
        ('event', '0003_auto_20201117_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributers',
            new_name='Contributer',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
