# Generated by Django 2.2.10 on 2020-11-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201117_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributer',
            name='event_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
