# Generated by Django 2.2.10 on 2020-12-31 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201117_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 0, 0)),
        ),
    ]
