# Generated by Django 2.2.10 on 2020-12-31 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_contributer_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 12, 0, 1)),
        ),
    ]
