# Generated by Django 2.2.10 on 2021-01-01 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20201231_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 0, 0)),
        ),
    ]
