# Generated by Django 2.2.10 on 2020-12-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0007_auto_20201115_1143'),
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_profile.Alumni_Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media.Post')),
            ],
        ),
    ]
