# Generated by Django 2.2.10 on 2020-12-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
