# Generated by Django 2.2.10 on 2020-12-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni_profile', '0007_auto_20201115_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('yearly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('life_time_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('yearly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('life_time_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni_profile.Alumni_Profile')),
                ('fee_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_fee.Fee_Info')),
            ],
        ),
    ]
