# Generated by Django 2.2.10 on 2020-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_fee', '0002_auto_20201202_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_fee',
            name='life_time_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='alumni_fee',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='alumni_fee',
            name='yearly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fee_info',
            name='life_time_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fee_info',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fee_info',
            name='yearly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
