# Generated by Django 2.2.10 on 2020-12-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_fee', '0005_alumni_fee_yearly_fee_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni_fee',
            name='yearly_fee_count',
        ),
        migrations.CreateModel(
            name='Alumni_Yearly_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField()),
                ('alumni_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_fee.Alumni_Fee')),
            ],
        ),
    ]
