# Generated by Django 2.2.10 on 2020-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='certificate',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
