# Generated by Django 2.2.10 on 2020-11-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0005_auto_20201029_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_profile',
            name='ask_for_update_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
