# Generated by Django 2.2.10 on 2020-11-15 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0006_auto_20201111_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to=settings.AUTH_USER_MODEL),
        ),
    ]
