# Generated by Django 2.2.10 on 2021-01-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0007_auto_20201115_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
    ]
