# Generated by Django 2.2.10 on 2021-01-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile', '0009_alumni_profile_social_media_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni_profile',
            name='social_media_links',
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='facebook',
            field=models.URLField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='linkdin',
            field=models.URLField(blank=True, max_length=60),
        ),
    ]
